# Generated by Django 3.1.4 on 2020-12-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='media/NoImage.jpg', upload_to='media/profiles/'),
        ),
    ]
