# Generated by Django 3.1.4 on 2020-12-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/NoImage.png', upload_to='media/'),
        ),
    ]
