# Generated by Django 3.1.4 on 2020-12-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20201216_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/NoImage.jpg', upload_to='media/'),
        ),
    ]
